version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: fitness-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workoutpal
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
